# Generated by Django 4.2.10 on 2025-05-07 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('okrapi', '0010_remove_okr_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_id', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_user_principal_name', models.EmailField(blank=True, max_length=254, null=True)),
                ('teams_profile_photo', models.URLField(blank=True, max_length=1024, null=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okrapi.businessunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
