# Generated by Django 4.2.10 on 2025-05-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamsprofile',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='teamsprofile',
            name='user',
        ),
    ]
