# Generated by Django 4.2.10 on 2025-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0002_remove_teamsprofile_business_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsprofile',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
