# Generated by Django 4.2.10 on 2025-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0003_teamsprofile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsprofile',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsprofile',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamsprofile',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsprofile',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
