# Generated by Django 4.2.10 on 2025-05-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0004_add_is_active_field'),
    ]

    operations = [
    ]
