# Generated by Django 4.2.10 on 2025-05-29 11:29

from django.db import migrations


def ensure_isactive_true(apps, schema_editor):
    TeamsProfile = apps.get_model('teamsauth', 'TeamsProfile')
    # Update all records to have isActive=True where it might be null
    TeamsProfile.objects.filter(isActive__isnull=True).update(isActive=True)


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0004_add_is_active_field'),
    ]

    operations = [
        migrations.RunPython(ensure_isactive_true),
    ]
