# Generated by Django 4.2.10 on 2025-05-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0005_ensure_isactive_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsprofile',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
