# Generated by Django 4.2.10 on 2025-05-29 17:15

from django.db import migrations, models

def set_is_active_true(apps, schema_editor):
    # Get the TeamsProfile model
    TeamsProfile = apps.get_model('teamsauth', 'TeamsProfile')
    
    # Update all records to have isActive=True
    TeamsProfile.objects.all().update(isActive=True)


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0005_ensure_isactive_field'),
    ]

    operations = [
        # First check if isActive field exists - if not, add it as nullable
        migrations.AddField(
            model_name='teamsprofile',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
        
        # Run function to set all existing records to have isActive=True
        migrations.RunPython(set_is_active_true),
        
        # Now update the field to be non-nullable with default=True
        migrations.AlterField(
            model_name='teamsprofile',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
