# Generated by Django 4.2.10 on 2025-06-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0005_ensure_isactive_true'),
        ('teamsauth', '0006_add_isactive_field'),
        ('teamsauth', '0006_add_isactive_field_non_nullable'),
    ]

    operations = [
    ]
