# Generated by Django 4.2.10 on 2025-06-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0007_merge_20250608_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.IntegerField(choices=[(0, 'Add Objective'), (1, 'Admin Master')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='teamsauth.teamsprofile')),
            ],
            options={
                'verbose_name': 'User Access Right',
                'verbose_name_plural': 'User Access Rights',
                'unique_together': {('user', 'access_id')},
            },
        ),
    ]
