# Generated by Django 4.2.10 on 2025-05-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0011_user_teams_profile_alter_log_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
