# Generated by Django 4.2.10 on 2025-05-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamsauth', '0003_teamsprofile_user_name'),
        ('okrapi', '0012_auto_20250509_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Submitted')], default=0)),
                ('manager_review', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_forms', to='teamsauth.teamsprofile')),
            ],
            options={
                'unique_together': {('user', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='OptionMapper',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMaster',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_name', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Descriptive'), (1, 'Multiple Choice')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='okr',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_okrs', through='okrapi.OkrUserMapping', to='teamsauth.teamsprofile'),
        ),
        migrations.CreateModel(
            name='UserAnswerData',
            fields=[
                ('uad_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_description', models.TextField(blank=True, max_length=250, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='okrapi.formdata')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='okrapi.optionmapper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okrapi.questionmaster')),
            ],
        ),
        migrations.AddField(
            model_name='optionmapper',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='okrapi.questionmaster'),
        ),
    ]
