# Generated by Django 4.2.10 on 2025-05-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0004_add_manager_review_models'),
        ('okrapi', '0015_add_manager_review_models'),
    ]

    operations = [
    ]
