# Generated by Django 4.2.10 on 2025-07-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0016_merge_20250515_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Planning', 'Planning'), ('Active', 'Active'), ('Hold', 'Hold'), ('Confirmation awaited', 'Confirmation awaited'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
    ]
