name: Keep Render Awake

on:
  schedule:
    - cron: "*/12 * * * *"  # Every 14 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the health-check endpoint
        run: |
          echo "Pinging Render backend to prevent sleep..."
          curl -s https://bd-okr.onrender.com/api/health/ || echo "Ping failed"
